#!/bin/bash
set -euxo pipefail

set +e
test ! -z "$(git diff --name-only HEAD)"
HAS_CHANGES=$?
set -e


FILENAME="profiles/$(git log -1 --format=%h)"

if [ "$HAS_CHANGES" -eq 0 ]; then
  FILENAME="$FILENAME-dirty"
fi

python -m cProfile -o "$FILENAME" main.py --no-file

